version: "3.9"
services:
    caddy:
        container_name: caddy
        image: caddy:2
        network_mode: host
        depends_on:
            - pds
        restart: unless-stopped
        volumes:
            - type: bind
              source: /pds/caddy/data
              target: /data
            - type: bind
              source: /pds/caddy/etc/caddy
              target: /etc/caddy
    pds:
        container_name: pds
        image: ghcr.io/hsrmk/pds:sha-842770577022925931d5424d5bcc2621b6ebbd53
        network_mode: host
        restart: unless-stopped
        volumes:
            - type: bind
              source: /pds
              target: /pds
        env_file:
            - /pds/pds.env
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower:latest
        network_mode: host
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        restart: unless-stopped
        environment:
            WATCHTOWER_CLEANUP: true
            WATCHTOWER_SCHEDULE: "@midnight"
